<?php

namespace UtilisateurBundle\Repository;

/**
 * CollocationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CollocationRepository extends \Doctrine\ORM\EntityRepository
{
}
