<?php

namespace UtilisateurBundle\Repository;

/**
 * NouveauteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NouveauteRepository extends \Doctrine\ORM\EntityRepository
{
}
